### ISSUE TITLE
Wyvern cant see that some games with linux installer has linux installer

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#17]
```
Baseball Stars 2 [2020914910]
Garou - Mark of the Wolves [1830215906]
Last Blade [2146639333]
Metal Slug [1136471182]
Metal Slug 2 [1241813850]
Metal Slug 3 [1370911530]
Metal Slug X [2046360890]
Shock Troopers [1633815479]
Shock Troopers: Second Squad [1816849333]
Twinkle Star Sprites  [1955376433]
```

these games all have linux installers, but they give the message

`This game does not support linux! Would you like to download the windows version to run under wine? [Y/n]`

On the webpage these games list OSX and Linux installers as unsupported extras

![image](https://user-images.githubusercontent.com/2087930/54758741-0e413e80-4bed-11e9-984e-bffa0536a3c0.png)
![image](https://user-images.githubusercontent.com/2087930/54758783-1e591e00-4bed-11e9-99a4-31c5aefb0106.png)

Thanks to @MajorDangerNine for discovering this

**Comment by nicohman** [comment]
Because these aren't actually shown as being game 'installers', there's really no way for me to automatically know that these are Linux installers. You can download them through the `extras` subcommand, though. These effectively are the same as wallpapers or soundtracks in the API. I could manually create an exception list that downloads these extras instead for only those games, but that seems kinda kludgy.

**Comment by sigboe** [comment]
What if you do check for extras, and see if there there are any `gog_*.sh` files?

**Comment by nicohman** [comment]
Without actually attempting a request to fetch one of the extras, I can't see the full filename. Having to make a full GOG request for every extra a game has would slow down the download process quite a bit.
