### ISSUE TITLE
Are both galaxy and non-galaxy installers avilable for download?

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#18]
https://github.com/dscharrer/innoextract/issues/79

The guy over at innoextract says that the installers that wyvern fetches are galaxy installers, and they are more different from normal innosetup files.

Can you see both in the API? can you maybe allow or even default to preferring non-galaxy setup files?

**Comment by nicohman** [comment]
AFAIK(and this is admittedly based off of my knowledge of an API that isn't exactly documented), there are two ways that I can access a game: Through the galaxy.gog.com API and the main API. The galaxy.gog.com API only supports windows and mac games, but also supports way easier delta updating. The other is the one that you get when you download  a game from the website, and there's only one version of any Linux game there. Wyvern downloads everything from the main website API, because the main focus is on Linux games. I don't believe that there are any other installers that are less galaxy than that. Do you know exactly how they are different/what's wrong with using them?

**Comment by sigboe** [comment]
The file directories inside the non-galaxy files are 
```
app/ #the whole game is here
tmp/ #temp data I guess, or data related to the installer
commondata/ #data related to the installer
```

In the galaxy setups, the files are all over the place, and assembled by the installer. And innoextract does not move the files around proper.
I have been able to workaround this. But I hoped I could just download the non-galaxy setups instead. If you want to default to the galaxy setup files. thats fine too, I just hope I could get the option :D

**Comment by nicohman** [comment]
In that case, it seems like this is either something that should be handled by innoextract, or a separate script, as I don’t really know anything about how the GOG windows installers work.
