### ISSUE TITLE
Failed to Connect to Demenses.net

### ISSUE THREAD

**Issue by sigboe** [nicohman/wyvern#32]
User @CountMetal opened an issue over at my place. https://github.com/sigboe/pie-galaxy/issues/11 where your site seams to be offline.

Will we be expecting this to come back up?

**Comment by Peneheals** [comment]
It is still offline :-/

**Comment by nicohman** [comment]
This went down when I took down my running instance of ravenserver. At this point, bringing back up the auto build and deploy for ARM would require setting up and paying for an extra running web server. Since I’m not actually part of the pie-galaxy project I don’t think that makes sense. The build script is public if somebody else wanted to though.

**Comment by sigboe** [comment]
I am now hosting a mirror at https://github.com/sigboe/wyvern/releases/ It is not auto updating though I am watching this repo
I could look into github CI but that may or may be for another day
